# Navigation Links
# The weight parameter defines the order the links appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: research
    weight: 20
  - name: People
    url: people
    weight: 40
  - name: Join Us
    url: join
    weight: 50
  - name: Variants
    url: variants
    weight: 30